# <font color='blue'>Data Science Academy - Big Data Real-Time Analytics com Python e Spark</font>
# <font color='blue'>Capítulo 3</font>

****** Este Jupyter Notebook foi atualizado para a versão 3.6.1. da Linguagem Python em 13/06/2017 ******

## NumPy

NumPy oferece sequências de elementos que são mais eficientes que sequências padrões em Python.

In [1]:
import sys
import numpy as np
print(sys.version)
np.__version__

3.6.1 |Anaconda 4.4.0 (x86_64)| (default, May 11 2017, 13:04:09) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]


'1.12.1'

In [2]:
# Criando um array NumPy
array1 = np.arange(15)

In [3]:
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [4]:
# Help
?array1

In [5]:
array1.mean()

7.0

In [6]:
array1.sum()

105

In [7]:
array1.min()

0

In [8]:
array1.max()

14

In [9]:
array1.std()

4.3204937989385739

## Utilizando List Compreheension em Arrays NumPy

In [10]:
# Utilizando lists compreheension em arrays NumPy
[x * x for x in array1]

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196]

In [11]:
# Utilizando lists compreheension em arrays NumPy
[x * x for x in array1 if x % 2 == 0]

[0, 4, 16, 36, 64, 100, 144, 196]

## Utilizando Função Lambda em Arrays NumPy

In [12]:
# Utilizando expressão lambda
list(filter(lambda x: x % 2 == 0, array1))

[0, 2, 4, 6, 8, 10, 12, 14]

In [13]:
# Atenção com a notação
array1 % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True], dtype=bool)

In [14]:
# # Atenção com a notação
array1[array1 % 2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14])

## Avaliando a Performance

In [15]:
# Performance usando list compreheension
%timeit [x for x in array1 if x % 2 == 0]

100000 loops, best of 3: 5.89 µs per loop


In [16]:
# Performance usando NumPy
%timeit array1[array1 % 2 == 0]

The slowest run took 8.40 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 2.84 µs per loop


## Usando Operadores Lógicos

In [17]:
array1 > 8

array([False, False, False, False, False, False, False, False, False,
        True,  True,  True,  True,  True,  True], dtype=bool)

In [18]:
array1[array1 > 8]

array([ 9, 10, 11, 12, 13, 14])

In [19]:
# Operador lógico and 
(array1 > 9) & (array1 < 12)

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True, False, False, False], dtype=bool)

In [20]:
# Operador lógico or
(array1 > 13) | (array1 < 12)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False, False,  True], dtype=bool)

In [21]:
# Operador lógico or
array1[(array1 > 13) | (array1 < 12)]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 14])

In [22]:
# Criando um array NumPy com list comprehension
array2 = np.array([x ** 3 for x in range(15)])

In [23]:
array2

array([   0,    1,    8,   27,   64,  125,  216,  343,  512,  729, 1000,
       1331, 1728, 2197, 2744])

In [24]:
# Criando um array NumPy com list comprehension
array2 = np.array([True for x in range(15)])

In [25]:
array2

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True], dtype=bool)

In [26]:
# Usando um array como índice para outro array
array1[array2]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

# Fim

### Obrigado - Data Science Academy - <a href=http://facebook.com/dsacademy>facebook.com/dsacademybr</a>