## NumPy

NumPy oferece sequências de elementos que são mais eficientes que sequências padrões em Python.

In [1]:
import sys
import numpy as np
print(sys.version)
np.__version__

3.11.7 (main, Dec 15 2023, 12:09:56) [Clang 14.0.6 ]


'2.0.0'

In [2]:
# Criando um array NumPy
array1 = np.arange(15)

In [3]:
array1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [4]:
# Help
?array1

Type:        ndarray
String form: [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
Length:      15
File:        ~/.local/share/virtualenvs/python_numpy_pandas_dsa-nLp2V0TY/lib/python3.11/site-packages/numpy/__init__.py
Docstring:  
ndarray(shape, dtype=float, buffer=None, offset=0,
        strides=None, order=None)

An array object represents a multidimensional, homogeneous array
of fixed-size items.  An associated data-type object describes the
format of each element in the array (its byte-order, how many bytes it
occupies in memory, whether it is an integer, a floating point number,
or something else, etc.)

Arrays should be constructed using `array`, `zeros` or `empty` (refer
to the See Also section below).  The parameters given here refer to
a low-level method (`ndarray(...)`) for instantiating an array.

For more information, refer to the `numpy` module and examine the
methods and attributes of an array.

Parameters
----------
(for the __new__ method; see Notes below)

shape : tuple

In [5]:
array1.mean()

np.float64(7.0)

In [6]:
array1.sum()

np.int64(105)

In [7]:
array1.min()

np.int64(0)

In [8]:
array1.max()

np.int64(14)

In [9]:
array1.std()

np.float64(4.320493798938574)

## Utilizando List Compreheension em Arrays NumPy

In [10]:
# Utilizando lists compreheension em arrays NumPy
[x * x for x in array1]

[np.int64(0),
 np.int64(1),
 np.int64(4),
 np.int64(9),
 np.int64(16),
 np.int64(25),
 np.int64(36),
 np.int64(49),
 np.int64(64),
 np.int64(81),
 np.int64(100),
 np.int64(121),
 np.int64(144),
 np.int64(169),
 np.int64(196)]

In [11]:
# Utilizando lists compreheension em arrays NumPy
[x * x for x in array1 if x % 2 == 0]

[np.int64(0),
 np.int64(4),
 np.int64(16),
 np.int64(36),
 np.int64(64),
 np.int64(100),
 np.int64(144),
 np.int64(196)]

## Utilizando Função Lambda em Arrays NumPy

In [12]:
# Utilizando expressão lambda
list(filter(lambda x: x % 2 == 0, array1))

[np.int64(0),
 np.int64(2),
 np.int64(4),
 np.int64(6),
 np.int64(8),
 np.int64(10),
 np.int64(12),
 np.int64(14)]

In [13]:
# Atenção com a notação
array1 % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True])

In [14]:
# # Atenção com a notação
array1[array1 % 2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14])

## Avaliando a Performance

In [15]:
# Performance usando list compreheension
%timeit [x for x in array1 if x % 2 == 0]

1.14 μs ± 15.5 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [16]:
# Performance usando NumPy
%timeit array1[array1 % 2 == 0]

949 ns ± 18 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


## Usando Operadores Lógicos

In [17]:
array1 > 8

array([False, False, False, False, False, False, False, False, False,
        True,  True,  True,  True,  True,  True])

In [18]:
array1[array1 > 8]

array([ 9, 10, 11, 12, 13, 14])

In [19]:
# Operador lógico and 
(array1 > 9) & (array1 < 12)

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True, False, False, False])

In [20]:
# Operador lógico or
(array1 > 13) | (array1 < 12)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True, False, False,  True])

In [21]:
# Operador lógico or
array1[(array1 > 13) | (array1 < 12)]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 14])

In [22]:
# Criando um array NumPy com list comprehension
array2 = np.array([x ** 3 for x in range(15)])

In [23]:
array2

array([   0,    1,    8,   27,   64,  125,  216,  343,  512,  729, 1000,
       1331, 1728, 2197, 2744])

In [24]:
# Criando um array NumPy com list comprehension
array2 = np.array([True for x in range(15)])

In [25]:
array2

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True])

In [26]:
# Usando um array como índice para outro array
array1[array2]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])