## NumPy

NumPy oferece sequências de elementos que são mais eficientes que sequências padrões em Python.

In [2]:
import sys
import numpy as np
print(sys.version)
np.__version__

3.11.7 (main, Dec 15 2023, 12:09:56) [Clang 14.0.6 ]


'2.0.0'

## Concatenando Arrays

In [3]:
array1 = np.ones(4)

In [4]:
array2 = np.arange(15)

In [5]:
array_conc = np.concatenate((array1, array2))

In [6]:
array_conc

array([ 1.,  1.,  1.,  1.,  0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,
        9., 10., 11., 12., 13., 14.])

## Joining Arrays

In [7]:
a = np.ones((3,3))
b = np.zeros((3,3))

In [8]:
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [9]:
print(b)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [10]:
?np.vstack

Signature:       np.vstack(tup, *, dtype=None, casting='same_kind')
Call signature:  np.vstack(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function vstack at 0x1085fab60>
File:            ~/.local/share/virtualenvs/python_numpy_pandas_dsa-nLp2V0TY/lib/python3.11/site-packages/numpy/_core/shape_base.py
Docstring:      
Stack arrays in sequence vertically (row wise).

This is equivalent to concatenation along the first axis after 1-D arrays
of shape `(N,)` have been reshaped to `(1,N)`. Rebuilds arrays divided by
`vsplit`.

This function makes most sense for arrays with up to 3 dimensions. For
instance, for pixel-data with a height (first axis), width (second axis),
and r/g/b channels (third axis). The functions `concatenate`, `stack` and
`block` provide more general stacking and concatenation operations.

Parameters
----------
tup : sequence of ndarrays
    The arrays must have the same shape along all but the first axis.
    1-D arrays must have the sam

In [11]:
?np.hstack

Signature:       np.hstack(tup, *, dtype=None, casting='same_kind')
Call signature:  np.hstack(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function hstack at 0x1085fac00>
File:            ~/.local/share/virtualenvs/python_numpy_pandas_dsa-nLp2V0TY/lib/python3.11/site-packages/numpy/_core/shape_base.py
Docstring:      
Stack arrays in sequence horizontally (column wise).

This is equivalent to concatenation along the second axis, except for 1-D
arrays where it concatenates along the first axis. Rebuilds arrays divided
by `hsplit`.

This function makes most sense for arrays with up to 3 dimensions. For
instance, for pixel-data with a height (first axis), width (second axis),
and r/g/b channels (third axis). The functions `concatenate`, `stack` and
`block` provide more general stacking and concatenation operations.

Parameters
----------
tup : sequence of ndarrays
    The arrays must have the same shape along all but the second axis,
    except 1-D arrays 

In [12]:
# Primeiro preenche as linhas
np.vstack((a,b))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [13]:
# Primeiro preenche as colunas
np.hstack((a,b))

array([[1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.]])

In [14]:
# Joining arrays
a = np.array([0, 1, 2])
b = np.array([3, 4, 5])
c = np.array([6, 7, 8])

In [15]:
?np.column_stack

Signature:       np.column_stack(tup)
Call signature:  np.column_stack(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function column_stack at 0x10875fec0>
File:            ~/.local/share/virtualenvs/python_numpy_pandas_dsa-nLp2V0TY/lib/python3.11/site-packages/numpy/lib/_shape_base_impl.py
Docstring:      
Stack 1-D arrays as columns into a 2-D array.

Take a sequence of 1-D arrays and stack them as columns
to make a single 2-D array. 2-D arrays are stacked as-is,
just like with `hstack`.  1-D arrays are turned into 2-D columns
first.

Parameters
----------
tup : sequence of 1-D or 2-D arrays.
    Arrays to stack. All of them must have the same first dimension.

Returns
-------
stacked : 2-D array
    The array formed by stacking the given arrays.

See Also
--------
stack, hstack, vstack, concatenate

Examples
--------
>>> a = np.array((1,2,3))
>>> b = np.array((2,3,4))
>>> np.column_stack((a,b))
array([[1, 2],
       [2, 3],
       [3, 4]])
Class docstri

In [16]:
?np.row_stack

Signature: np.row_stack(tup, *, dtype=None, casting='same_kind')
Docstring:
Stack arrays in sequence vertically (row wise).

This is equivalent to concatenation along the first axis after 1-D arrays
of shape `(N,)` have been reshaped to `(1,N)`. Rebuilds arrays divided by
`vsplit`.

This function makes most sense for arrays with up to 3 dimensions. For
instance, for pixel-data with a height (first axis), width (second axis),
and r/g/b channels (third axis). The functions `concatenate`, `stack` and
`block` provide more general stacking and concatenation operations.

Parameters
----------
tup : sequence of ndarrays
    The arrays must have the same shape along all but the first axis.
    1-D arrays must have the same length.

dtype : str or dtype
    If provided, the destination array will have this dtype. Cannot be
    provided together with `out`.

    .. versionadded:: 1.24

casting : {'no', 'equiv', 'safe', 'same_kind', 'unsafe'}, optional
    Controls what kind of data casting may o

In [17]:
np.column_stack((a, b, c))

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [18]:
np.row_stack((a, b, c))

/var/folders/5z/nms2vp9s0_1dm1130xnk264w0000gn/T/ipykernel_51739/3069552908.py:1: DeprecationWarning: `row_stack` alias is deprecated. Use `np.vstack` directly.
  np.row_stack((a, b, c))


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## Split Arrays

In [19]:
array3 = np.arange(16).reshape((4,4)); array3

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [20]:
[array3_p1, array3_p2] = np.hsplit(array3, 2)

In [21]:
array3_p1

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [22]:
array3_p2

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [23]:
[array3_p1, array3_p2] = np.vsplit(array3, 2)

In [24]:
array3_p1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [25]:
array3_p2

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

## Gravando e Cerragendo Dados com NumPy

In [26]:
dados = array3

In [27]:
np.save('dados_saved_v1', dados)

In [28]:
loaded_data = np.load('dados_saved_v1.npy')

In [29]:
loaded_data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])