# <font color='white'>Capítulo 2</font>

Para gerar um arquivo pdf a partir do Jupyter Notebook, você precisar ter instalado em seu computador:
    
    MiKTeX e Pandoc (Windows)
    LaTeX e Pandoc (Mac)
    TeX Live e Pandoc (linux)
    
Neste link você encontra todas as informações: http://pandoc.org/installing.html

## Computação com Numpy

In [2]:
# Importando o módulo Numpy
import numpy as np

<h2>Criando Estruturas de Dados NumPy</h2>

In [3]:
# Criando array unidimensional
array1 = np.array([10, 20, 30, 40]) 

In [4]:
# Criando array bi-dimensional
array2 = np.array([[100, 83, 15],[42, 78, 0]]) 

In [5]:
array1

array([10, 20, 30, 40])

In [6]:
array2

array([[100,  83,  15],
       [ 42,  78,   0]])

In [7]:
# Verificando o formato (shape) do array
array1.shape

(4,)

In [8]:
# Verificando o formato (shape) do array
array2.shape

(2, 3)

In [9]:
# Verificando o número de dimensões
array2.ndim

2

<h2>Em Python TUDO é objeto, com métodos e atributos</h2>

### Método - realiza ação no objeto
### Atributo - característica do objeto

In [10]:
# Método - retorna maior objeto do array
array2.max()

np.int64(100)

In [11]:
# Atributo
array2.ndim

2

<h2>Criando estruturas de dados com arange</h2>

In [12]:
array3 = np.arange(15)

In [13]:
array3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [16]:
# Usando start/end (exclusive)
array4 = np.arange(0, 16, 5)

In [17]:
array4

array([ 0,  5, 10, 15])

<h2>Criando estruturas de dados com linspace</h2>

In [18]:
# Argumentos: (start, end, number of elements)
array5 = np.linspace(0, 3, 4); array5

array([0., 1., 2., 3.])

<h2>Criando estruturas de dados com outras funções</h2>

<h3>numpy.zeros</h3>

In [19]:
# Array 10x8 de zeros
array6 = np.zeros((10, 8)); array6

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

<h3>numpy.ones</h3>

In [20]:
# Array 2x3x2 de 1's
array7 = np.ones((2, 3, 2)); array7

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

<h3>numpy.eye</h3>

In [21]:
# Produz uma Identitiy Matrix 
array8 = np.eye(3); array8

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

<h3>numpy.diag</h3>

In [22]:
# Matriz diagonal
array9 = np.diag((2,1,4,6)); array9

array([[2, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 6]])

<h3>numpy.random.rand</h3>

In [28]:
# A função rand(n) produz uma sequência de números uniformemente distribuídos com range de 0 a n
np.random.seed(100) # Set seed
array10 = np.random.rand(5); array10

array([0.54340494, 0.27836939, 0.42451759, 0.84477613, 0.00471886])

In [29]:
# A função randn(n) produz uma sequência de números com distribuição normal (Gaussian)
array11 = np.random.randn(5); array11

array([ 0.35467445, -0.78606433, -0.2318722 ,  0.20797568,  0.93580797])

<h3>numpy.empty</h3>

In [30]:
array12 = np.empty((3,2)); array12

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

<h3>numpy.tile</h3>

In [31]:
np.array([[9, 4], [3, 7]])

array([[9, 4],
       [3, 7]])

In [32]:
np.tile(np.array([[9, 4], [3, 7]]), 4)

array([[9, 4, 9, 4, 9, 4, 9, 4],
       [3, 7, 3, 7, 3, 7, 3, 7]])

In [33]:
np.tile(np.array([[9, 4], [3, 7]]), (2,2))

array([[9, 4, 9, 4],
       [3, 7, 3, 7],
       [9, 4, 9, 4],
       [3, 7, 3, 7]])

<h2>Tipos de Dados NumPy</h2>

In [43]:
array13 = np.array([8, -3, 5.4, 9], dtype = 'float')

In [44]:
array13

array([ 8. , -3. ,  5.4,  9. ])

In [45]:
array13.dtype

dtype('float64')

In [46]:
array14 = np.array([2, 4, 6, 8])

In [47]:
array14

array([2, 4, 6, 8])

In [48]:
array14.dtype

dtype('int64')

In [49]:
array15 = np.array([2.0, 4, 6, 8])

In [50]:
array15.dtype

dtype('float64')

In [51]:
array16 = np.array(['Análise','de','Dados','com Python'])

In [52]:
array16.dtype

dtype('<U10')

In [53]:
array17 = np.array([True, False, True])

In [54]:
array17.dtype

dtype('bool')

In [55]:
array18 = np.array([7, -3, 5.24])

In [56]:
array18.dtype

dtype('float64')

In [57]:
array18.astype(int)

array([ 7, -3,  5])

<h2>Operações com Arrays</h2>

In [60]:
# Array começando por 0, com 30 elementos e multiplicado po 5
array19 = np.arange(0, 30) * 10

In [61]:
array19

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120,
       130, 140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240, 250,
       260, 270, 280, 290])

In [62]:
array19 = np.arange(0, 30)

In [63]:
array19

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [66]:
# Elevando um array a potência
array20 = np.arange(5) ** 2

In [67]:
array20

array([ 0,  1,  4,  9, 16])

In [72]:
# Somando um número a cada elemento do array
array21 = np.arange(0, 30) + 1

In [73]:
array21

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [74]:
array22 = np.arange(0, 30,3) + 3
array23 = np.arange(1,11)

In [75]:
array22

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [76]:
array23

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [77]:
# Subtração
array22 - array23

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [78]:
# Soma
array22 + array23

array([ 4,  8, 12, 16, 20, 24, 28, 32, 36, 40])

In [79]:
# Divisão
array22 / array23

array([3., 3., 3., 3., 3., 3., 3., 3., 3., 3.])

In [80]:
# Multiplicação
array22 * array23

array([  3,  12,  27,  48,  75, 108, 147, 192, 243, 300])

In [81]:
# Podemos ainda comprar arrays
array22 > array23

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

In [82]:
arr1 = np.array([True,False,True,False])
arr2 = np.array([False,False,True, False])
np.logical_and(arr1, arr2)

array([False, False,  True, False])

### Podemos criar arrays com Python, sem usar o módulo NumPy. Porém o NumPy é muito mais rápido

In [83]:
array_numpy = np.arange(1000)
%timeit array_numpy ** 4

2.06 μs ± 7.36 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [84]:
array_python = range(1000)
%timeit [array_python[i] ** 4 for i in array_python]

55.8 μs ± 269 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


A métrica µs significa microsegundos.